version: '3'

services:
  frontend:
    container_name: create-react-app-test
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - PORT=8000
    stdin_open: true
volumes:
  node-modules:
